config/routes.rb
Photosharing::Application.routes.draw do
  get "home/index"

  devise_for :people
  
  resources :sperrens

  resources :people

  resources :comments

  resources :photos do
  	resources :comments
  end

  resources :albums do
  	resources :photos
  end
  

  root :to => "albums#index"

end

app/models/album.rb
class Album < ActiveRecord::Base
  # validation for attributes
  validates :title, :presence => true
  
  # 1:n relation between 'album' and 'photo'
  # add this line in model 'album': 
  # ... belongs_to :album
  has_many :photos
  
  def created_at_date
  	created_at.to_datetime.strftime("%A %d %b %Y").squeeze(' ')
  end
  
  def number_of_photos
  	photos.count
  end
  
  def last_photo
  	photos.last
  end
  
  def pageForUpdate(order, per_page)
    position = Album.where("#{order} <= ?", self.send(order)).count
    ((0.0+position)/per_page).ceil
  end
  
  def pageForDelete(order, per_page)
    position = Album.where("#{order} < ?", self.send(order)).count
    ((0.0+position)/per_page).ceil
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_filter :authenticate_person! 

  # GET /albums
  # GET /albums.xml
  def index
    @albums = Album.paginate(:page => params[:page], :per_page => 5)

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /albums/1
  # GET /albums/1.xml
  def show
    @album = Album.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /albums/new
  # GET /albums/new.xml
  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
  end

  # POST /albums
  # POST /albums.xml
  def create
    @album = Album.new(params[:album])

    respond_to do |format|
      if @album.save
        @goto_page = @album.pageForUpdate(:id, 5)
        if @goto_page < 1
      		@goto_page = 1
      	end
        format.html { redirect_to(albums_url(:page => @goto_page), :notice => 'Album was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.xml
  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        @goto_page = @album.pageForUpdate(:id, 5)
        if @goto_page < 1
      		@goto_page = 1
      	end
        format.html { redirect_to(albums_url(:page => @goto_page), :notice => 'Album was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.xml
  def destroy
    @album = Album.find(params[:id])
    @goto_page = @album.pageForDelete(:id, 5)
    if @goto_page < 1
      @goto_page = 1
	end
    
    @album.destroy
    respond_to do |format|
      format.html { redirect_to(albums_url(:page => @goto_page), :notice => 'Album was successfully deleted.') }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
<div class="column_left">
	<div class="form">
		<div class="caption"><%= f.label :title, "Titel" %><font class="point">*</font></div>
		<%= f.text_field :title, :class => "text_field" %>
		<div class="caption"><%= f.label :description, "Beschreibung" %></div>
		<%= f.text_area :description, :class => "text_area" %>
		<div id="not_null"> 
			<span>Mit <font class="point">*</font> gekennzeichnete Felder sind Pflichtangaben</span>
		</div> 
	</div>
</div> 
<% if !notice %>
<% if @album.errors.any? %>
<div id="error"> 
	<span>
		<% @album.errors.full_messages.each do |msg| %>
        	<%= msg %><br>
      	<% end %>
	</span>
</div> 
<% end %>
<% end %>
<% end %>

app/views/albums/edit.html.erb
<div id="page_title">
	<div id="page_title_content">
		<span class="title_black">Album #<%= @album.id %> ändern</span>
	</div>
	<div id="page_title_actions">
		<div class="actions_save"> 
			<span><%= link_to_function 'Speichern', ["edit_album_", @album.id, ".submit()"], :class => "link_white" %></span>
		</div> 
		<div class="actions_cancel"> 
			<span><%= link_to 'Zurück', albums_path, :class => "link_white" %></span>
		</div> 
	</div> 
</div>
<div id="page_text">
	<%= render 'form' %>
</div>

app/views/albums/index.html.erb
<div id="page_title">
	<div id="page_title_content">
		<span class="title_black">Alben auflisten</span>
	</div>
	<div id="page_title_actions">
		<div id="page_title_actions_container">
			<div class="actions_170"> 
				<span><%= link_to 'Album hinzufügen', new_album_path, :class => "link_white" %></span>
			</div> 
			<% if @albums.total_pages > 1 %>
			<div class="actions_150"> 
				<%= will_paginate @albums %>
			</div> 
			<% end %>
		</div>
	</div> 
</div>
<div id="page_text">
	<div class="row">
	<% @albums.each do |album| %>
		<div class="cell_album">
			<%= link_to album_photos_url(album) do %>
			<div class="cell_album_image">
				<% if album.last_photo %>
				<%= image_tag(album.last_photo.image.url(:thumb)) %>
				<% end %>
			</div>
			<% end %>
			<% if album.number_of_photos > 0 %>
			<div class="cell_album_items">
				<span><%= album.number_of_photos %></span>
			</div>
			<% end %>
			<div class="cell_album_title">
				<span><%= album.title %></span>
			</div>
			<div class="cell_album_links">
				<%= link_to 'Ändern', edit_album_path(album) %>&nbsp;|&nbsp;<%= link_to 'Löschen', album, :confirm => 'Sind Sie sicher?', :method => :delete %>
			</div>
		</div>
	<% end %>
	</div> 
	<% if !notice %>
	<% if Album.count < 1 %>
	<div id="error"> 
		<span>Es wurden keine Alben gefunden</span>
	</div> 
	<% end %>
	<% end %>
</div>

app/views/albums/new.html.erb
<div id="page_title">
	<div id="page_title_content">
		<span class="title_black">Album hinzufügen</span>
	</div>
	<div id="page_title_actions">
		<div class="actions_save"> 
			<span><%= link_to_function 'Speichern', "new_album.submit()", :class => "link_white" %></span>
		</div> 
		<div class="actions_cancel"> 
			<span><%= link_to 'Zurück', albums_path, :class => "link_white" %></span>
		</div> 
	</div> 
</div>
<div id="page_text">
	<%= render 'form' %>
</div>