config/routes.rb
Photosharing::Application.routes.draw do
  get "home/index"

  devise_for :people
  
  resources :sperrens

  resources :people

  resources :comments

  resources :photos do
  	resources :comments
  end

  resources :albums do
  	resources :photos
  end
  

  root :to => "albums#index"

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  # add file as property 
  has_attached_file :image, :styles => { :thumb => "130x130", :medium => "360x360", :large => "520x520"}
  
  # protect some of attributes of file
  attr_protected :image_file_name, :image_content_type, :image_size
  
  # validation for attributes
  validates :title, :presence => true
  
  # validation for file
  validates_attachment_presence :image
  validates_attachment_content_type :image, :content_type => [ 'image/jpeg', 'image/png' ]
  validates_attachment_size :image, :less_than => 5.megabytes
  
  # 1:n relation between 'comment' and 'user'
  # add this line in model 'user': 
  # ... has_many :photos
  belongs_to :album
  
  # 1:n relation between 'photo' and 'user'
  # add this line in model 'user': 
  # ... has_many :photos
  belongs_to :person
  
  # 1:n relation between 'comment' and 'photo'
  # add this line in model 'comment': 
  # ... has_many :photos
  belongs_to :comment
  
  # 1:n relation between 'comment' and 'photo'
  # add this line in model 'comment': 
  # ... belongs_to :photo
  has_many :comments
  
  def created_at_date
  	created_at.to_datetime.strftime("%A %d %b %Y").squeeze(' ')
  end
  
  def number_of_comments
  	comments.count
  end
  
  def is_owner(current_person)
  	person.id == current_person.id
  end
  
  def complain
 	 Emailer.complain_email( "http://photosharing.com/bild.jpg", "Because of").deliver
  end
  
  def pageForUpdate(order, per_page)
    position = Photo.where("album_id = #{album.id} AND #{order} <= ?", self.send(order)).count
    ((0.0+position)/per_page).ceil
  end
  
  def pageForDelete(order, per_page)
    position = Photo.where("album_id = #{album.id} AND #{order} < ?", self.send(order)).count
    ((0.0+position)/per_page).ceil
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_filter :authenticate_person! 

  # GET /photos
  # GET /photos.xml
  def index
    @album = Album.find(params[:album_id])
    @photos = @album.photos.paginate(:page => params[:page], :per_page => 5)

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /photos/1
  # GET /photos/1.xml
  def show
    @photo = Photo.find(params[:id])
    @album = Album.find(params[:album_id])
    @person = Person.find(@photo.person.id)
    @comments = @photo.comments.paginate(:page => params[:page], :per_page => 5)

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /photos/new
  # GET /photos/new.xml
  def new
    @photo = Photo.new
    @album = Album.find(params[:album_id])
    @person = Person.find(current_person.id)

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
    @album = Album.find(params[:album_id])
    @person = Person.find(@photo.person.id)
  end

  # POST /photos
  # POST /photos.xml
  def create
  	@album = Album.find(params[:album_id])
    @photo = Photo.new(params[:photo])
    @photo.album = @album
    @photo.person = Person.find(current_person.id)

    respond_to do |format|
      if @photo.save
      	@goto_page = @photo.pageForUpdate(:id, 5)
      	if @goto_page < 1
      		@goto_page = 1
      	end
        format.html { redirect_to(album_photos_url(@album, :page => @goto_page), :notice => 'Photo was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.xml
  def update
    @album = Album.find(params[:album_id])
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
      	@goto_page = @photo.pageForUpdate(:id, 5)
      	if @goto_page < 1
      		@goto_page = 1
      	end
        format.html { redirect_to(album_photos_url(@album, :page => @goto_page), :notice => 'Photo was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.xml
  def destroy
    @album = Album.find(params[:album_id])
    @photo = Photo.find(params[:id])
    @goto_page = @photo.pageForDelete(:id, 5)
    if @goto_page < 1
      @goto_page = 1
    end
      	
    @photo.destroy
    respond_to do |format|
	  format.html { redirect_to(album_photos_path(@album, :page => @goto_page), :notice => 'Photo was successfully deleted.') }
    end
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_comment.html.erb
<div class="column_left">
	<div class="cell_picture">
		<div class="cell_picture_image">
			<%= link_to_function(image_tag(@photo.image.url(:medium)), "show_full_image_popup()") %>
		</div>
		<div class="cell_picture_title">
			<span><%= @photo.title %></span>
		</div>
		<div class="cell_picture_author">
			<span><%= @photo.person.username %></span>
		</div>
		<div class="cell_picture_date">
			<span><%= @photo.created_at_date %></span>
		</div>
	</div>
</div>
<div class="column_right">
	<div class="row">
		<% @comments.each do |comment| %>
		<div class="cell_comment">
			<div class="cell_comment_header">
				<div class="cell_comment_date">
					<span><%= comment.created_at_date %></span>
				</div>
				<div class="cell_comment_user">
					<span><%= comment.person.username %></span>
				</div>
			</div>
			<div class="cell_comment_body">
				<div class="cell_comment_text">
					<span><%= comment.body %></span>
				</div>
				<%if comment.is_author(current_person) %>
				<div class="cell_comment_links">
					<%= link_to 'Ändern', edit_comment_path(comment) %>&nbsp;|&nbsp;<%= link_to 'Löschen', comment, :confirm => 'Sind Sie sicher?', :method => :delete %>
				</div>
				<% end %>
				<% if !comment.is_author(current_person) %>
				<div class="cell_comment_links">
					<%= link_to 'Melden', complain_comment_path(comment), :confirm => 'Sind Sie sicher?' %>
				</div>
				<% end %>
			</div>
		</div>
		<% end %>
	</div>
</div>
<% if !notice %>
<% if @comments.count < 1 %>
<div id="error"> 
	<span>Es wurden keine Kommentare gefunden</span>
</div> 
<% end %>
<% end %>

app/views/photos/_form.html.erb
<%= form_for [@album, @photo], :html => { :multipart => true } do |f| %>
<div class="column_left">
	<div class="form">
		<div class="caption"><%= f.label :title, "Titel" %><font class="point">*</font></div>
		<%= f.text_field :title, :class => "text_field" %>
		<div class="caption"><%= f.label :image, "Bild" %><font class="point">*</font></div>
		<%= f.file_field :image, :class => "file_field" %>
		<div id="not_null"> 
			<span>Mit <font class="point">*</font> gekennzeichnete Felder sind Pflichtangaben</span>
		</div> 
	</div>
</div>
<% if !notice %>
<% if @photo.errors.any? %>
<div id="error"> 
	<span>
		<% @photo.errors.full_messages.each do |msg| %>
        <%= msg %><br>
      	<% end %>
	</span>
</div> 
<% end %>
<% end %>
<% end %>












<!--
<%= form_for [@album, @photo], :html => { :multipart => true } do |f| %>
<% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table cellpadding="10" width="600">
    <tr>
      <td bgcolor="#DDDDDD">
    
        <div class="field">
          <%= f.label :title %><br />
          <%= f.text_field :title %>
        </div>
  
        <div class="field">
          <%= f.label :image %><br />
	      <%= f.file_field :image %>
        </div>
        
        <br>
        
        <div class="actions">
          <%= f.submit %>
        </div>
  
      </td>
    </tr>
  </table>

<% end %>
//-->

app/views/photos/edit.html.erb
<div id="page_title">
	<div id="page_title_content">
		<span class="title_black">Foto #<%= @photo.id %> ändern</span>
	</div>
	<div id="page_title_actions">
		<div class="actions_save"> 
			<span><%= link_to_function 'Speichern', ["edit_photo_", @photo.id, ".submit()"], :class => "link_white" %></span>
		</div> 
		<div class="actions_cancel"> 
			<span><%= link_to 'Zurück', album_photos_path(@album), :class => "link_white" %></span>
		</div> 
	</div> 
</div>
<div id="page_text">
	<%= render 'form' %>
</div>

app/views/photos/index.html.erb
<div id="page_title">
	<div id="page_title_content">
		<span class="title_black">Fotos im Album #<%= @album.id %></span>
	</div>
	<div id="page_title_actions">
		<div id="page_title_actions_container">
			<div class="actions_150"> 
				<span><%= link_to 'Foto hinzufügen', new_album_photo_path(@album), :class => "link_white" %></span>
			</div> 
			<div class="actions_90"> 
				<span><%= link_to 'Zurück', albums_path, :class => "link_white" %></span>
			</div> 
			<% if @photos.total_pages > 1 %>
			<div class="actions_150"> 
				<%= will_paginate @photos %>
			</div> 
			<% end %>
		</div> 
	</div>
</div>
<div id="page_text">
	<div class="row">
	<% @photos.each do |photo| %>
		<div class="cell_photo">
			<%= link_to album_photo_path(@album, photo) do %>
			<div class="cell_photo_image">
				<%= image_tag photo.image.url(:thumb) %>
			</div>
			<% end %>
			<% if photo.number_of_comments > 0 %>
			<div class="cell_photo_items">
				<span><%= photo.number_of_comments %></span>
			</div>
			<% end %>
			<div class="cell_photo_title">
				<span><%= photo.title %></span>
			</div>
			<%if photo.is_owner(current_person) %>
			<div class="cell_photo_links">
				<%= link_to 'Ändern', edit_album_photo_path(@album, photo) %>&nbsp;|&nbsp;<%= link_to 'Löschen', [@album, photo], :confirm => 'Sind Sie sicher?', :method => :delete %>
			</div>
			<% end %>
		</div>
	<% end %>
	</div> 
	<% if !notice %>
	<% if @photos.count < 1 %>
	<div id="error"> 
		<span>Es wurden keine Fotos gefunden</span>
	</div> 
	<% end %>
	<% end %>
</div>

app/views/photos/new.html.erb
<div id="page_title">
	<div id="page_title_content">
		<span class="title_black">Foto hinzufügen</span>
	</div>
	<div id="page_title_actions">
		<div class="actions_save"> 
			<span><%= link_to_function 'Speichern', "new_photo.submit()", :class => "link_white" %></span>
		</div> 
		<div class="actions_cancel"> 
			<span><%= link_to 'Zurück', album_photos_path(@album), :class => "link_white" %></span>
		</div> 
	</div> 
</div>
<div id="page_text">
	<%= render 'form' %>
</div>

app/views/photos/show.html.erb
<div id="page_title">
	<div id="page_title_content">
		<span class="title_black">Foto #<%= @photo.id %> anzeigen</span>
	</div>
	<div id="page_title_actions">
		<div id="page_title_actions_container">
			<div class="actions_210"> 
				<span><%= link_to 'Kommentar hinzufügen', new_photo_comment_path(@photo), :class => "link_white" %></span>
			</div>
			<div class="actions_90"> 
				<span><%= link_to 'Zurück', album_photos_path(@album), :class => "link_white" %></span>
			</div> 
			<% if @comments.total_pages > 1 %>
			<div class="actions_150"> 
				<%= will_paginate @comments %>
			</div> 
			<% end %>
		</div>
	</div> 
</div>
<div id="page_text">
	<%= render 'comment' %>
</div>
<div id="full_image_container" class="container_hidden">
	<div id="full_image_background"></div>
	<div id="full_image"><%= link_to_function(image_tag(@photo.image.url(:large)), "show_full_image_popup()") %></div>
</div>