config/routes.rb
Photosharing::Application.routes.draw do
  get "home/index"

  devise_for :people
  
  resources :sperrens

  resources :people

  resources :comments

  resources :photos do
  	resources :comments
  end

  resources :albums do
  	resources :photos
  end
  

  root :to => "albums#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Photosharing</title>
	  <%= stylesheet_link_tag :all %>
	  <%= javascript_include_tag :defaults %>
	  <%= csrf_meta_tag %>
	</head>
	<body bgcolor="#006699" id="body" class="body_scrolling">
		<div id="top_container"> 
			<div id="top_container_content">
				<% if person_signed_in? %>
    				<span class="text_white"><span class="text_light_blue">Herzlich Willkommen <%= current_person.username %></span>&nbsp;<%= link_to "Profil", edit_person_path(current_person), :class => "link_white" %>&nbsp;|&nbsp;<%= link_to "Abmelden", destroy_person_session_path, :class => "link_white" %></span>
  				<% end %>
			</div>
		</div> 
		<div id="middle_container"> 
			<div>
				<img src="/images/roundedbox_ro.png" id="corner_top_right">
			</div> 
			<div id="page_content">
				<%= yield %>
			</div>
			<% if notice %>
				<div id="success"> 
					<span><%= notice %></span>
				</div> 
			<% end %>
			<div>
				<img src="/images/roundedbox_ru.png" id="corner_bottom_right">
			</div> 
		</div>
		<div id="bottom_container"> 
			<div>
				<span class="text_white">Arthur Helmel, Bastian Landherr, Kevin Virmani. Entwickelt für die Vorlesung Softwareengineering II. Alle Rechte vorbehalten.</span>
			</div> 
		</div>
	</body>
</html>